source 'https://rubygems.org'
ruby '2.2.4'

gem "sinatra"
gem "json"

gem "one_up"

group :development do
  gem "shotgun"
end

group :development, :test do
  gem "rspec", "~> 3.0"
  gem "guard-rspec"
  gem "rspec-given"
  gem "pry"
end